services:
  - type: web
    name: danco-logistics
    env: python
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python manage.py migrate --run-syncdb; python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "True"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
    autoDeploy: true
